"""
Synthetic ad-impression log generator.

Real click logs (Avazu/Criteo) need a Kaggle account and a multi-GB download,
which doesn't reproduce in CI. This generator produces a smaller dataset with
the same *structural* properties that make CTR modeling hard:

  - extreme class imbalance (~4-8% click rate)
  - high-cardinality categorical IDs (site, app, device) that must be hashed
  - a real temporal axis, so a random split would leak and a time split won't
  - user-level heterogeneity (some users click much more than others), so
    user-history features carry real signal
  - a nonlinear, noisy relationship between features and clicks, so a linear
    model underfits and a raw (uncalibrated) score systematically misestimates
    true probability -- which is the whole point of the calibration stage
  - a genuine per-user x ad-category preference (not just "this ad is
    popular" or "this user clicks a lot"), so a personalized ranker has
    real signal to exploit that a global popularity baseline structurally
    cannot see -- without this, the honest result is that popularity wins,
    which is a fine finding but not an interesting demo

Every number the README reports is computed from data generated by this
script, via a fixed --seed, so the whole pipeline is reproducible end-to-end
without external downloads or credentials.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import polars as pl

N_USERS = 2_000  # kept close to N_ADS so a ~10-day window gives each user
# enough repeat impressions per category (~15) for the user_cat_hist_ctr
# feature to carry real signal -- at real Avazu/Criteo scale (millions of
# users), the equivalent feature needs weeks of history or a learned
# embedding instead of a raw historical-CTR aggregate; see docs/design.md.
N_ADS = 2_000
N_SITES = 500
N_DEVICES = 3_000
N_DAYS = 10
ROWS_PER_DAY = 60_000
N_CATEGORIES = 20


def _rng(seed: int) -> np.random.Generator:
    return np.random.default_rng(seed)


def generate(n_days: int, rows_per_day: int, seed: int) -> pl.DataFrame:
    rng = _rng(seed)

    # Per-user/ad/site log-odds contributions, fixed for the whole dataset
    # so user-history and ad-quality features carry real signal rather than
    # pure noise. These are additive in logit space (not multiplicative log
    # of a lognormal), which keeps the average click rate anchored near the
    # BASE_LOGIT target regardless of variance -- an earlier version of this
    # generator multiplied log(lognormal) terms together, which silently
    # collapsed the average CTR to ~0.001%.
    user_effect = rng.normal(0, 0.6, size=N_USERS)
    ad_effect = rng.normal(0, 0.5, size=N_ADS)
    site_effect = rng.normal(0, 0.3, size=N_SITES)
    ad_category = rng.integers(0, N_CATEGORIES, size=N_ADS)

    # Each user has their own affinity for each category (e.g. this user
    # loves "sports", is neutral on "finance") -- a real interaction effect
    # that only shows up when you know *both* who the user is and what
    # category the ad is. A model that only sees "is this ad popular"
    # (popularity baseline) or "does this user click a lot" (a weak model)
    # cannot see this; a model with a user x category feature can.
    user_category_affinity = rng.normal(0, 1.0, size=(N_USERS, N_CATEGORIES))

    BASE_LOGIT = -3.7  # anchors average CTR to ~5%, verified empirically

    frames = []
    for day in range(n_days):
        n = rows_per_day
        user_id = rng.integers(0, N_USERS, size=n)
        ad_id = rng.integers(0, N_ADS, size=n)
        site_id = rng.integers(0, N_SITES, size=n)
        device_id = rng.integers(0, N_DEVICES, size=n)
        hour = rng.integers(0, 24, size=n)

        # Evening hours convert better.
        hour_effect = 0.3 * np.sin((hour - 6) / 24 * 2 * np.pi)
        cat = ad_category[ad_id]
        pref_effect = user_category_affinity[user_id, cat]

        logit = (
            user_effect[user_id]
            + ad_effect[ad_id]
            + site_effect[site_id]
            + pref_effect
            + hour_effect
            + BASE_LOGIT
        )
        p_click = 1 / (1 + np.exp(-logit))
        click = rng.binomial(1, p_click)

        frames.append(
            pl.DataFrame(
                {
                    "day": np.full(n, day, dtype=np.int32),
                    "hour": hour.astype(np.int32),
                    "user_id": user_id.astype(np.int32),
                    "ad_id": ad_id.astype(np.int32),
                    "site_id": site_id.astype(np.int32),
                    "device_id": device_id.astype(np.int32),
                    "ad_category": cat.astype(np.int32),
                    "click": click.astype(np.int8),
                }
            )
        )

    df = pl.concat(frames)
    # Global row order = arrival order; row_id encodes it for a stable
    # time-respecting split even within a day.
    df = df.with_row_index("row_id")
    return df


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="data/clicks.parquet")
    ap.add_argument("--days", type=int, default=N_DAYS)
    ap.add_argument("--rows-per-day", type=int, default=ROWS_PER_DAY)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    df = generate(args.days, args.rows_per_day, args.seed)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    df.write_parquet(out)
    print(f"wrote {df.height:,} rows ({df['click'].mean():.3%} click rate) -> {out}")


if __name__ == "__main__":
    main()
